### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by tommymetz** [DrewDahlman/wp-headless#2]
Hey we are using this plugin at Cactus and it's awesome! I think we need to extend it to allow uploading other content. More specifically an XML Sitemap. Is there an action I can hook to for when the publishing happens? So I can generate a sitemap and upload it to S3 as well? Wanted to ask before I start digging into it.

**Comment by DrewDahlman** [comment]
Hey! Awesome, tell Andrew I say hello!

For a hook to generate a site map it wouldn’t be too wild, I’m assuming you want to shape it based on your json content? 

It may involve extending the plugin a bit for generation but all of the relevant code is there for iterating over content

**Comment by DrewDahlman** [comment]
If you were to add this feature I would start with the [parsePost function](https://github.com/DrewDahlman/wp-headless/blob/master/wp-headless/wp-headless.php#L129-L178) which is the recursive function that pulls out posts and gets all the info.

From there it would be pretty easy to create an object and pass that along with the JSON array for content and push in everything you'd need to create the XML.

Then you'd have a new function that would create the file you want ( probably a temp file just like the JSON ) and then when the JSON completes upload create a new uploader and upload your XML file, then delete just like what's done with the JSON. That can be found [here](https://github.com/DrewDahlman/wp-headless/blob/master/wp-headless/wp-headless.php#L91-L111)

**Comment by tommymetz** [comment]
Awesome Drew thanks for the info! Makes perfect sense.

**Comment by DrewDahlman** [comment]
Let me know if you roll this in - would love to see the implementation or if you'd like to contribute it as potentially an option / extension.

**Comment by tommymetz** [comment]
4sho!

**Comment by tommymetz** [comment]
Have a look at our implementation if you like. I also added you as a collaborator: https://github.com/cactus-denver/wp-headless/commit/5153a126223b28fda1f981b0a7a2b3d9afe0eebc . The readme (within the wp-headless folder) has an overview of what I did. Would be cool to take this a little further and add some extra dashboard settings. We can see about doing that, just needed a quick solution for now.
