### ISSUE TITLE
20 post limit in Publish Settings

### ISSUE THREAD

**Issue by BDMayhem** [DrewDahlman/wp-headless#5]
I'm not seeing a way to select/add all posts under Publish Settings, and the generated list only contains the first 20 posts alphabetically.  How does one add more posts without having to search for them manually?  Thanks!

**Comment by DrewDahlman** [comment]
Hmm if you’re talking the selector for the posts you should be able to scroll down and it will load more.. is that not happening?

**Comment by BDMayhem** [comment]
I just checked it out, and it's working in Wordpress 4.9.1, but when I update to 5.1.1, it fails.

**Comment by DrewDahlman** [comment]
ahh - that may be an issue with ACF - if you add your license and pull the update I would assume it will work. ACF had to make changes to account for WP5.0+
